{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arkime.configMapName" . }} # Use helper for name
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
data:
  config.ini: |
{{ .Values.configMap.config | nindent 4 }}
{{- end -}}
