{{- if .Values.wise.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkime.fullname" . }}-wise
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
    app.kubernetes.io/component: wise
  {{- with .Values.wise.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.wise.replicas }}
  {{- with .Values.wise.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.wise.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arkime.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wise
  template:
    metadata:
      labels:
        {{- include "arkime.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: wise
        {{- with .Values.wise.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.wise.additionalAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arkime.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wise.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.wise.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.wise.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.wise.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.wise.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.wise.schedulerName }}
      schedulerName: {{ . | quote }}
      {{- end }}
      {{- with .Values.wise.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: arkime-wise
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          {{- toYaml .Values.wise.command | nindent 10 }}
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          {{- range .Values.wise.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          # Ensure ARKIME_wiseService__webBasePath is set from the specific value
          - name: ARKIME_wiseService__webBasePath
            value: {{ .Values.wise.webBasePath | quote }}
          {{- if .Values.env }} # Global envs
            {{- range .Values.env }}
            {{- if ne .name "ARKIME_wiseService__webBasePath" }} # Avoid duplicating if present in global
          - name: {{ .name }}
            value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- with .Values.wise.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - name: arkime-config
            mountPath: /opt/arkime/etc/
          {{- if .Values.wise.extraVolumeMounts }}
            {{- toYaml .Values.wise.extraVolumeMounts | nindent 10 }}
          {{- end }}
        {{- with .Values.wise.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.wise.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          runAsNonRoot: true
          # runAsUser: 1001 # OpenShift assigns
          # runAsGroup: 1001 # OpenShift assigns
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      volumes:
      - name: arkime-config
        configMap:
          name: {{ include "arkime.configMapName" . }} # Use helper
      {{- if .Values.wise.extraVolumes }}
        {{- toYaml .Values.wise.extraVolumes | nindent 6 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkime.fullname" . }}-wise
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
  {{- with .Values.wise.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "arkime.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wise
  {{- with .Values.wise.service.ports }}
  ports:
    {{- toYaml . | nindent 12 }}
  {{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "arkime.fullname" . }}-wise
  labels:
    {{- include "arkime.labels" . | nindent 4 }}
    app.kubernetes.io/component: wise
spec:
  {{- with .Values.wise.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.wise.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arkime.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wise
{{- end }}
